version: '3.9'

services:
  postgres: 
    image: postgres:15
    restart: always
    env_file:
      - .env.development.local
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-homework

  redis:
    image: redis:6.2
    restart: always
    env_file:
      - .env.development.local
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - nestjs-homework

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    env_file:
      - .env.development.local
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data

volumes:
  postgres_data:
  redis_data:
  minio_storage:

networks:
  nestjs-homework:
    # external: true
      